### ISSUE TITLE
Title Formating

### ISSUE THREAD

**Issue by P-DR0ZD** [Seneca-CDOT/topics-in-open-source-2022#1]

**Comment by humphd** [comment]
@P-DR0ZD can you add some detail here?  I'm not sure what you're referring to in this issue.  Which title?  What formatting?

**Comment by P-DR0ZD** [comment]
@humphd sorry I accidentally put my lab 1 issue in the wrong repo Im unsure on how to remove it

**Comment by humphd** [comment]
Gotcha, no problem.  I'll close.
